name: Deploy Release
on:
  push:
    branches:
      - release
jobs:
  deploy_release:
    name: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: install dependency npm
        run: yarn

      - name: build release env dist file
        run: yarn build:release

      - name: upload dist to bj
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_ACCESS_KEY_SECRET }}
        run: |
          aws --region=${{ secrets.PROD_BJ_AWS_DEFAULT_REGION }} s3 sync ./dist s3://${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_BUCKET }}/longbridge-cloud/ --exclude "*.map" --cache-control max-age=31536000
          aws --region=${{ secrets.PROD_BJ_AWS_DEFAULT_REGION }} s3 cp ./dist/docs/index.html s3://${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_BUCKET }}/longbridge-cloud/ --cache-control no-cache
          aws --region=${{ secrets.PROD_BJ_AWS_DEFAULT_REGION }} s3 cp ./dist/en/docs/index.html s3://${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_BUCKET }}/longbridge-cloud/en/ --cache-control no-cache
          aws --region=${{ secrets.PROD_BJ_AWS_DEFAULT_REGION }} s3 cp ./dist/zh-HK/docs/index.html s3://${{ secrets.FE_S3_OPEN_STATIC_PROD_BJ_BUCKET }}/longbridge-cloud/zh-HK/ --cache-control no-cache
